---
  - hosts: storage
    any_errors_fatal: true
    name: "Bootstrap Persistent Storage Cluster"
    become: yes
    
    roles:
      - role: packages-glusterfs
        when: allow_package_installation|bool == true
      - glusterfs

  - hosts: master
    any_errors_fatal: true
    name: "Create NFS service on the cluster"
    run_once: true
    become: yes
    roles:
      - glusterfs-k8s
